services:
  - type: web
    name: workout-planner
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 app:app
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: workout-planner-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.7
